from .constants import (
    BASE_DIR, INTERFACE_DIR, ASSETS_DIR,
    APP_NAME, APP_VERSION, ICON_PATH,
    DB_CONFIG,
    SHADOW_BLUR_NORMAL, SHADOW_OFFSET_NORMAL, SHADOW_ALPHA_NORMAL,
    SHADOW_BLUR_HOVER,  SHADOW_OFFSET_HOVER,  SHADOW_ALPHA_HOVER,
    CARD_HEIGHT, CARD_MIN_WIDTH, CARD_BORDER_R,
    BTN_ICON_SIZE, BTN_ROUND_SIZE, BTN_ROUND_RADIUS,
    SIDEBAR_EXPANDED, SIDEBAR_COLLAPSED, SIDEBAR_ANIM_MS, SIDEBAR_TEXT_THRESHOLD,
    ADD_BTN_SIZE, ADD_BTN_RADIUS,
    CIRCLE_TIMER_SIZE, CIRCLE_TIMER_THICKNESS, CIRCLE_TIMER_ANIM_MS,
    CIRCLE_TIMER_FONT_SIZE, CIRCLE_FONT_FAMILY,
    DIALOG_W, DIALOG_H, DIALOG_PADDING, DIALOG_SPACING,
    DIALOG_INPUT_RADIUS, DIALOG_INPUT_FONT,
    TIME_INPUT_BTN_W, TIME_INPUT_BTN_H,
    TIME_INPUT_FONT, TIME_INPUT_LABEL_FONT, TIME_INPUT_ARROW_FONT,
    GRID_SPACING,
    DRAG_MIN_DISTANCE, DRAG_OPACITY,
    CARD_HOVER_ANIM_MS, CARD_HOVER_OFFSET,
)

from .theme import (
    ThemeConfig,
    COLOR_BG_PRIMARY, COLOR_BG_CARD, COLOR_BG_SURFACE,
    COLOR_BG_BTN, COLOR_BG_BTN_HOVER,
    COLOR_BG_NAV, COLOR_BG_NAV_HOVER, COLOR_BG_NAV_ACTIVE, COLOR_BG_NAV_PRESSED,
    COLOR_BG_SURFACE_HOVER, COLOR_BG_OVERLAY_HOVER,
    COLOR_ACCENT, COLOR_ACCENT_HOVER, COLOR_ACCENT_DISABLED,
    COLOR_TEXT_PRIMARY, COLOR_TEXT_SECONDARY, COLOR_TEXT_MUTED, COLOR_TEXT_DISABLED,
    COLOR_SCROLLBAR_BG, COLOR_SCROLLBAR_TRACK, COLOR_SCROLLBAR_THUMB, COLOR_SCROLLBAR_HOVER,
)

from .user_settings import (
    UserSettings,
    POMODORO_WORK, POMODORO_BREAK,
    AFK_TIMEOUT,
    DEFAULT_TIMER_MINUTES,
    TIMER_PRESETS,
)

from .settings_manager import SettingsManager, settings_manager